/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatResponse {
  chat_id: number;
  is_active: boolean;
  created_at: string;
}
