/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ExpandedDocumentResponse {
  document_id: number;
  minio_url: string;
  filename: string;
  created_at: string;
  is_general: boolean;
  document_length: number;
}
