/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MessageResponse } from './messageResponse';

export interface ExpandedChatResponse {
  chat_id: number;
  is_active: boolean;
  created_at: string;
  prompt: string;
  messages?: MessageResponse[];
}
