/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MessageType } from "./messageType";
import type { MessageResponseHiddenComments } from "./messageResponseHiddenComments";

export interface MessageResponse {
    content: string;
    documents_ids: number[];
    message_id: number;
    message_type: MessageType;
    created_at: string;
    hidden_comments: MessageResponseHiddenComments;
}
