/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

export interface UserResponse {
  username: string;
  email: string;
  role?: Role;
  id: number;
}
