/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    BaseMessage,
    BodyUploadDocumentApiV1DocumentPost,
    ChatResponse,
    DocumentResponse,
    ExpandedChatResponse,
    ExpandedDocumentResponse,
    HTTPValidationError,
    PromptID,
    Token,
    UserCreate,
    UserLogin,
    UserResponse,
} from "../types";

import { customFetch } from "./libs/fetch";

/**
 * @summary Register User
 */
export type registerUserApiV1AuthRegisterPostResponse200 = {
    data: UserResponse;
    status: 200;
};

export type registerUserApiV1AuthRegisterPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type registerUserApiV1AuthRegisterPostResponseSuccess =
    registerUserApiV1AuthRegisterPostResponse200 & {
        headers: Headers;
    };
export type registerUserApiV1AuthRegisterPostResponseError =
    registerUserApiV1AuthRegisterPostResponse422 & {
        headers: Headers;
    };

export type registerUserApiV1AuthRegisterPostResponse =
    | registerUserApiV1AuthRegisterPostResponseSuccess
    | registerUserApiV1AuthRegisterPostResponseError;

export const getRegisterUserApiV1AuthRegisterPostUrl = () => {
    return `/api/v1/auth/register`;
};

export const registerUserApiV1AuthRegisterPost = async (
    userCreate: UserCreate,
    options?: RequestInit
): Promise<registerUserApiV1AuthRegisterPostResponse> => {
    return customFetch<registerUserApiV1AuthRegisterPostResponse>(
        getRegisterUserApiV1AuthRegisterPostUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(userCreate),
        }
    );
};

export const getRegisterUserApiV1AuthRegisterPostMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof registerUserApiV1AuthRegisterPost>>,
        TError,
        { data: UserCreate },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof registerUserApiV1AuthRegisterPost>>,
    TError,
    { data: UserCreate },
    TContext
> => {
    const mutationKey = ["registerUserApiV1AuthRegisterPost"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof registerUserApiV1AuthRegisterPost>>,
        { data: UserCreate }
    > = (props) => {
        const { data } = props ?? {};

        return registerUserApiV1AuthRegisterPost(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type RegisterUserApiV1AuthRegisterPostMutationResult = NonNullable<
    Awaited<ReturnType<typeof registerUserApiV1AuthRegisterPost>>
>;
export type RegisterUserApiV1AuthRegisterPostMutationBody = UserCreate;
export type RegisterUserApiV1AuthRegisterPostMutationError =
    HTTPValidationError;

/**
 * @summary Register User
 */
export const useRegisterUserApiV1AuthRegisterPost = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof registerUserApiV1AuthRegisterPost>>,
            TError,
            { data: UserCreate },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof registerUserApiV1AuthRegisterPost>>,
    TError,
    { data: UserCreate },
    TContext
> => {
    const mutationOptions =
        getRegisterUserApiV1AuthRegisterPostMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Login User
 */
export type loginUserApiV1AuthLoginPostResponse200 = {
    data: Token;
    status: 200;
};

export type loginUserApiV1AuthLoginPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type loginUserApiV1AuthLoginPostResponseSuccess =
    loginUserApiV1AuthLoginPostResponse200 & {
        headers: Headers;
    };
export type loginUserApiV1AuthLoginPostResponseError =
    loginUserApiV1AuthLoginPostResponse422 & {
        headers: Headers;
    };

export type loginUserApiV1AuthLoginPostResponse =
    | loginUserApiV1AuthLoginPostResponseSuccess
    | loginUserApiV1AuthLoginPostResponseError;

export const getLoginUserApiV1AuthLoginPostUrl = () => {
    return `/api/v1/auth/login`;
};

export const loginUserApiV1AuthLoginPost = async (
    userLogin: UserLogin,
    options?: RequestInit
): Promise<loginUserApiV1AuthLoginPostResponse> => {
    return customFetch<loginUserApiV1AuthLoginPostResponse>(
        getLoginUserApiV1AuthLoginPostUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(userLogin),
        }
    );
};

export const getLoginUserApiV1AuthLoginPostMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof loginUserApiV1AuthLoginPost>>,
        TError,
        { data: UserLogin },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof loginUserApiV1AuthLoginPost>>,
    TError,
    { data: UserLogin },
    TContext
> => {
    const mutationKey = ["loginUserApiV1AuthLoginPost"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof loginUserApiV1AuthLoginPost>>,
        { data: UserLogin }
    > = (props) => {
        const { data } = props ?? {};

        return loginUserApiV1AuthLoginPost(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type LoginUserApiV1AuthLoginPostMutationResult = NonNullable<
    Awaited<ReturnType<typeof loginUserApiV1AuthLoginPost>>
>;
export type LoginUserApiV1AuthLoginPostMutationBody = UserLogin;
export type LoginUserApiV1AuthLoginPostMutationError = HTTPValidationError;

/**
 * @summary Login User
 */
export const useLoginUserApiV1AuthLoginPost = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof loginUserApiV1AuthLoginPost>>,
            TError,
            { data: UserLogin },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof loginUserApiV1AuthLoginPost>>,
    TError,
    { data: UserLogin },
    TContext
> => {
    const mutationOptions =
        getLoginUserApiV1AuthLoginPostMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Read Users Me
 */
export type readUsersMeApiV1AuthMeGetResponse200 = {
    data: UserResponse;
    status: 200;
};

export type readUsersMeApiV1AuthMeGetResponseSuccess =
    readUsersMeApiV1AuthMeGetResponse200 & {
        headers: Headers;
    };
export type readUsersMeApiV1AuthMeGetResponse =
    readUsersMeApiV1AuthMeGetResponseSuccess;

export const getReadUsersMeApiV1AuthMeGetUrl = () => {
    return `/api/v1/auth/me`;
};

export const readUsersMeApiV1AuthMeGet = async (
    options?: RequestInit
): Promise<readUsersMeApiV1AuthMeGetResponse> => {
    return customFetch<readUsersMeApiV1AuthMeGetResponse>(
        getReadUsersMeApiV1AuthMeGetUrl(),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getReadUsersMeApiV1AuthMeGetQueryKey = () => {
    return [`/api/v1/auth/me`] as const;
};

export const getReadUsersMeApiV1AuthMeGetQueryOptions = <
    TData = Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getReadUsersMeApiV1AuthMeGetQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>
    > = ({ signal }) => readUsersMeApiV1AuthMeGet(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type ReadUsersMeApiV1AuthMeGetQueryResult = NonNullable<
    Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>
>;
export type ReadUsersMeApiV1AuthMeGetQueryError = unknown;

export function useReadUsersMeApiV1AuthMeGet<
    TData = Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
                    TError,
                    Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
};
export function useReadUsersMeApiV1AuthMeGet<
    TData = Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
                    TError,
                    Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useReadUsersMeApiV1AuthMeGet<
    TData = Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Read Users Me
 */

export function useReadUsersMeApiV1AuthMeGet<
    TData = Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof readUsersMeApiV1AuthMeGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getReadUsersMeApiV1AuthMeGetQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Get All Chats
 */
export type getAllChatsApiV1ChatGetResponse200 = {
    data: ChatResponse[];
    status: 200;
};

export type getAllChatsApiV1ChatGetResponseSuccess =
    getAllChatsApiV1ChatGetResponse200 & {
        headers: Headers;
    };
export type getAllChatsApiV1ChatGetResponse =
    getAllChatsApiV1ChatGetResponseSuccess;

export const getGetAllChatsApiV1ChatGetUrl = () => {
    return `/api/v1/chat`;
};

export const getAllChatsApiV1ChatGet = async (
    options?: RequestInit
): Promise<getAllChatsApiV1ChatGetResponse> => {
    return customFetch<getAllChatsApiV1ChatGetResponse>(
        getGetAllChatsApiV1ChatGetUrl(),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetAllChatsApiV1ChatGetQueryKey = () => {
    return [`/api/v1/chat`] as const;
};

export const getGetAllChatsApiV1ChatGetQueryOptions = <
    TData = Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetAllChatsApiV1ChatGetQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>
    > = ({ signal }) => getAllChatsApiV1ChatGet(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAllChatsApiV1ChatGetQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>
>;
export type GetAllChatsApiV1ChatGetQueryError = unknown;

export function useGetAllChatsApiV1ChatGet<
    TData = Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
                    TError,
                    Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
};
export function useGetAllChatsApiV1ChatGet<
    TData = Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
                    TError,
                    Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAllChatsApiV1ChatGet<
    TData = Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get All Chats
 */

export function useGetAllChatsApiV1ChatGet<
    TData = Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAllChatsApiV1ChatGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetAllChatsApiV1ChatGetQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create Chat
 */
export type createChatApiV1ChatPostResponse201 = {
    data: ExpandedChatResponse;
    status: 201;
};

export type createChatApiV1ChatPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type createChatApiV1ChatPostResponseSuccess =
    createChatApiV1ChatPostResponse201 & {
        headers: Headers;
    };
export type createChatApiV1ChatPostResponseError =
    createChatApiV1ChatPostResponse422 & {
        headers: Headers;
    };

export type createChatApiV1ChatPostResponse =
    | createChatApiV1ChatPostResponseSuccess
    | createChatApiV1ChatPostResponseError;

export const getCreateChatApiV1ChatPostUrl = () => {
    return `/api/v1/chat`;
};

export const createChatApiV1ChatPost = async (
    promptID: PromptID,
    options?: RequestInit
): Promise<createChatApiV1ChatPostResponse> => {
    return customFetch<createChatApiV1ChatPostResponse>(
        getCreateChatApiV1ChatPostUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(promptID),
        }
    );
};

export const getCreateChatApiV1ChatPostMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
        TError,
        { data: PromptID },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
    TError,
    { data: PromptID },
    TContext
> => {
    const mutationKey = ["createChatApiV1ChatPost"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
        { data: PromptID }
    > = (props) => {
        const { data } = props ?? {};

        return createChatApiV1ChatPost(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateChatApiV1ChatPostMutationResult = NonNullable<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>
>;
export type CreateChatApiV1ChatPostMutationBody = PromptID;
export type CreateChatApiV1ChatPostMutationError = HTTPValidationError;

/**
 * @summary Create Chat
 */
export const useCreateChatApiV1ChatPost = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
            TError,
            { data: PromptID },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
    TError,
    { data: PromptID },
    TContext
> => {
    const mutationOptions = getCreateChatApiV1ChatPostMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Chat
 */
export type getChatApiV1ChatChatIdGetResponse200 = {
    data: ExpandedChatResponse;
    status: 200;
};

export type getChatApiV1ChatChatIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type getChatApiV1ChatChatIdGetResponseSuccess =
    getChatApiV1ChatChatIdGetResponse200 & {
        headers: Headers;
    };
export type getChatApiV1ChatChatIdGetResponseError =
    getChatApiV1ChatChatIdGetResponse422 & {
        headers: Headers;
    };

export type getChatApiV1ChatChatIdGetResponse =
    | getChatApiV1ChatChatIdGetResponseSuccess
    | getChatApiV1ChatChatIdGetResponseError;

export const getGetChatApiV1ChatChatIdGetUrl = (chatId: number) => {
    return `/api/v1/chat/${chatId}`;
};

export const getChatApiV1ChatChatIdGet = async (
    chatId: number,
    options?: RequestInit
): Promise<getChatApiV1ChatChatIdGetResponse> => {
    return customFetch<getChatApiV1ChatChatIdGetResponse>(
        getGetChatApiV1ChatChatIdGetUrl(chatId),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetChatApiV1ChatChatIdGetQueryKey = (chatId?: number) => {
    return [`/api/v1/chat/${chatId}`] as const;
};

export const getGetChatApiV1ChatChatIdGetQueryOptions = <
    TData = Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
    TError = HTTPValidationError,
>(
    chatId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                TError,
                TData
            >
        >;
    }
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetChatApiV1ChatChatIdGetQueryKey(chatId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>
    > = ({ signal }) => getChatApiV1ChatChatIdGet(chatId, signal);

    return {
        queryKey,
        queryFn,
        enabled: !!chatId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChatApiV1ChatChatIdGetQueryResult = NonNullable<
    Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>
>;
export type GetChatApiV1ChatChatIdGetQueryError = HTTPValidationError;

export function useGetChatApiV1ChatChatIdGet<
    TData = Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
    TError = HTTPValidationError,
>(
    chatId: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                    TError,
                    Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
};
export function useGetChatApiV1ChatChatIdGet<
    TData = Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
    TError = HTTPValidationError,
>(
    chatId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                    TError,
                    Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChatApiV1ChatChatIdGet<
    TData = Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
    TError = HTTPValidationError,
>(
    chatId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Chat
 */

export function useGetChatApiV1ChatChatIdGet<
    TData = Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
    TError = HTTPValidationError,
>(
    chatId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getChatApiV1ChatChatIdGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetChatApiV1ChatChatIdGetQueryOptions(
        chatId,
        options
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Delete Chat
 */
export type deleteChatApiV1ChatChatIdDeleteResponse204 = {
    data: void;
    status: 204;
};

export type deleteChatApiV1ChatChatIdDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type deleteChatApiV1ChatChatIdDeleteResponseSuccess =
    deleteChatApiV1ChatChatIdDeleteResponse204 & {
        headers: Headers;
    };
export type deleteChatApiV1ChatChatIdDeleteResponseError =
    deleteChatApiV1ChatChatIdDeleteResponse422 & {
        headers: Headers;
    };

export type deleteChatApiV1ChatChatIdDeleteResponse =
    | deleteChatApiV1ChatChatIdDeleteResponseSuccess
    | deleteChatApiV1ChatChatIdDeleteResponseError;

export const getDeleteChatApiV1ChatChatIdDeleteUrl = (chatId: number) => {
    return `/api/v1/chat/${chatId}`;
};

export const deleteChatApiV1ChatChatIdDelete = async (
    chatId: number,
    options?: RequestInit
): Promise<deleteChatApiV1ChatChatIdDeleteResponse> => {
    return customFetch<deleteChatApiV1ChatChatIdDeleteResponse>(
        getDeleteChatApiV1ChatChatIdDeleteUrl(chatId),
        {
            ...options,
            method: "DELETE",
        }
    );
};

export const getDeleteChatApiV1ChatChatIdDeleteMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
        TError,
        { chatId: number },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
    TError,
    { chatId: number },
    TContext
> => {
    const mutationKey = ["deleteChatApiV1ChatChatIdDelete"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
        { chatId: number }
    > = (props) => {
        const { chatId } = props ?? {};

        return deleteChatApiV1ChatChatIdDelete(chatId);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteChatApiV1ChatChatIdDeleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>
>;

export type DeleteChatApiV1ChatChatIdDeleteMutationError = HTTPValidationError;

/**
 * @summary Delete Chat
 */
export const useDeleteChatApiV1ChatChatIdDelete = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
            TError,
            { chatId: number },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
    TError,
    { chatId: number },
    TContext
> => {
    const mutationOptions =
        getDeleteChatApiV1ChatChatIdDeleteMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Create Message
 */
export type createMessageApiV1ChatChatIdMessagePostResponse200 = {
    data: unknown;
    status: 200;
};

export type createMessageApiV1ChatChatIdMessagePostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type createMessageApiV1ChatChatIdMessagePostResponseSuccess =
    createMessageApiV1ChatChatIdMessagePostResponse200 & {
        headers: Headers;
    };
export type createMessageApiV1ChatChatIdMessagePostResponseError =
    createMessageApiV1ChatChatIdMessagePostResponse422 & {
        headers: Headers;
    };

export type createMessageApiV1ChatChatIdMessagePostResponse =
    | createMessageApiV1ChatChatIdMessagePostResponseSuccess
    | createMessageApiV1ChatChatIdMessagePostResponseError;

export const getCreateMessageApiV1ChatChatIdMessagePostUrl = (
    chatId: number
) => {
    return `/api/v1/chat/${chatId}/message`;
};

export const createMessageApiV1ChatChatIdMessagePost = async (
    chatId: number,
    baseMessage: BaseMessage,
    options?: RequestInit
): Promise<createMessageApiV1ChatChatIdMessagePostResponse> => {
    return customFetch<createMessageApiV1ChatChatIdMessagePostResponse>(
        getCreateMessageApiV1ChatChatIdMessagePostUrl(chatId),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(baseMessage),
        }
    );
};

export const getCreateMessageApiV1ChatChatIdMessagePostMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createMessageApiV1ChatChatIdMessagePost>>,
        TError,
        { chatId: number; data: BaseMessage },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createMessageApiV1ChatChatIdMessagePost>>,
    TError,
    { chatId: number; data: BaseMessage },
    TContext
> => {
    const mutationKey = ["createMessageApiV1ChatChatIdMessagePost"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createMessageApiV1ChatChatIdMessagePost>>,
        { chatId: number; data: BaseMessage }
    > = (props) => {
        const { chatId, data } = props ?? {};

        return createMessageApiV1ChatChatIdMessagePost(chatId, data);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateMessageApiV1ChatChatIdMessagePostMutationResult = NonNullable<
    Awaited<ReturnType<typeof createMessageApiV1ChatChatIdMessagePost>>
>;
export type CreateMessageApiV1ChatChatIdMessagePostMutationBody = BaseMessage;
export type CreateMessageApiV1ChatChatIdMessagePostMutationError =
    HTTPValidationError;

/**
 * @summary Create Message
 */
export const useCreateMessageApiV1ChatChatIdMessagePost = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createMessageApiV1ChatChatIdMessagePost>>,
            TError,
            { chatId: number; data: BaseMessage },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createMessageApiV1ChatChatIdMessagePost>>,
    TError,
    { chatId: number; data: BaseMessage },
    TContext
> => {
    const mutationOptions =
        getCreateMessageApiV1ChatChatIdMessagePostMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Documents For User
 */
export type getDocumentsForUserApiV1DocumentGetResponse200 = {
    data: DocumentResponse[];
    status: 200;
};

export type getDocumentsForUserApiV1DocumentGetResponseSuccess =
    getDocumentsForUserApiV1DocumentGetResponse200 & {
        headers: Headers;
    };
export type getDocumentsForUserApiV1DocumentGetResponse =
    getDocumentsForUserApiV1DocumentGetResponseSuccess;

export const getGetDocumentsForUserApiV1DocumentGetUrl = () => {
    return `/api/v1/document`;
};

export const getDocumentsForUserApiV1DocumentGet = async (
    options?: RequestInit
): Promise<getDocumentsForUserApiV1DocumentGetResponse> => {
    return customFetch<getDocumentsForUserApiV1DocumentGetResponse>(
        getGetDocumentsForUserApiV1DocumentGetUrl(),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetDocumentsForUserApiV1DocumentGetQueryKey = () => {
    return [`/api/v1/document`] as const;
};

export const getGetDocumentsForUserApiV1DocumentGetQueryOptions = <
    TData = Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getGetDocumentsForUserApiV1DocumentGetQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>
    > = ({ signal }) => getDocumentsForUserApiV1DocumentGet(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetDocumentsForUserApiV1DocumentGetQueryResult = NonNullable<
    Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>
>;
export type GetDocumentsForUserApiV1DocumentGetQueryError = unknown;

export function useGetDocumentsForUserApiV1DocumentGet<
    TData = Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getDocumentsForUserApiV1DocumentGet>
                    >,
                    TError,
                    Awaited<
                        ReturnType<typeof getDocumentsForUserApiV1DocumentGet>
                    >
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
};
export function useGetDocumentsForUserApiV1DocumentGet<
    TData = Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getDocumentsForUserApiV1DocumentGet>
                    >,
                    TError,
                    Awaited<
                        ReturnType<typeof getDocumentsForUserApiV1DocumentGet>
                    >
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetDocumentsForUserApiV1DocumentGet<
    TData = Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Documents For User
 */

export function useGetDocumentsForUserApiV1DocumentGet<
    TData = Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentsForUserApiV1DocumentGet>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions =
        getGetDocumentsForUserApiV1DocumentGetQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Upload Document
 */
export type uploadDocumentApiV1DocumentPostResponse200 = {
    data: DocumentResponse;
    status: 200;
};

export type uploadDocumentApiV1DocumentPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type uploadDocumentApiV1DocumentPostResponseSuccess =
    uploadDocumentApiV1DocumentPostResponse200 & {
        headers: Headers;
    };
export type uploadDocumentApiV1DocumentPostResponseError =
    uploadDocumentApiV1DocumentPostResponse422 & {
        headers: Headers;
    };

export type uploadDocumentApiV1DocumentPostResponse =
    | uploadDocumentApiV1DocumentPostResponseSuccess
    | uploadDocumentApiV1DocumentPostResponseError;

export const getUploadDocumentApiV1DocumentPostUrl = () => {
    return `/api/v1/document`;
};

export const uploadDocumentApiV1DocumentPost = async (
    bodyUploadDocumentApiV1DocumentPost: BodyUploadDocumentApiV1DocumentPost,
    options?: RequestInit
): Promise<uploadDocumentApiV1DocumentPostResponse> => {
    const formData = new FormData();
    formData.append(`file`, bodyUploadDocumentApiV1DocumentPost.file);

    return customFetch<uploadDocumentApiV1DocumentPostResponse>(
        getUploadDocumentApiV1DocumentPostUrl(),
        {
            ...options,
            method: "POST",
            body: formData,
        }
    );
};

export const getUploadDocumentApiV1DocumentPostMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof uploadDocumentApiV1DocumentPost>>,
        TError,
        { data: BodyUploadDocumentApiV1DocumentPost },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof uploadDocumentApiV1DocumentPost>>,
    TError,
    { data: BodyUploadDocumentApiV1DocumentPost },
    TContext
> => {
    const mutationKey = ["uploadDocumentApiV1DocumentPost"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof uploadDocumentApiV1DocumentPost>>,
        { data: BodyUploadDocumentApiV1DocumentPost }
    > = (props) => {
        const { data } = props ?? {};

        return uploadDocumentApiV1DocumentPost(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type UploadDocumentApiV1DocumentPostMutationResult = NonNullable<
    Awaited<ReturnType<typeof uploadDocumentApiV1DocumentPost>>
>;
export type UploadDocumentApiV1DocumentPostMutationBody =
    BodyUploadDocumentApiV1DocumentPost;
export type UploadDocumentApiV1DocumentPostMutationError = HTTPValidationError;

/**
 * @summary Upload Document
 */
export const useUploadDocumentApiV1DocumentPost = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof uploadDocumentApiV1DocumentPost>>,
            TError,
            { data: BodyUploadDocumentApiV1DocumentPost },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof uploadDocumentApiV1DocumentPost>>,
    TError,
    { data: BodyUploadDocumentApiV1DocumentPost },
    TContext
> => {
    const mutationOptions =
        getUploadDocumentApiV1DocumentPostMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Document
 */
export type getDocumentApiV1DocumentDocumentIdGetResponse200 = {
    data: ExpandedDocumentResponse;
    status: 200;
};

export type getDocumentApiV1DocumentDocumentIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type getDocumentApiV1DocumentDocumentIdGetResponseSuccess =
    getDocumentApiV1DocumentDocumentIdGetResponse200 & {
        headers: Headers;
    };
export type getDocumentApiV1DocumentDocumentIdGetResponseError =
    getDocumentApiV1DocumentDocumentIdGetResponse422 & {
        headers: Headers;
    };

export type getDocumentApiV1DocumentDocumentIdGetResponse =
    | getDocumentApiV1DocumentDocumentIdGetResponseSuccess
    | getDocumentApiV1DocumentDocumentIdGetResponseError;

export const getGetDocumentApiV1DocumentDocumentIdGetUrl = (
    documentId: number
) => {
    return `/api/v1/document/${documentId}`;
};

export const getDocumentApiV1DocumentDocumentIdGet = async (
    documentId: number,
    options?: RequestInit
): Promise<getDocumentApiV1DocumentDocumentIdGetResponse> => {
    return customFetch<getDocumentApiV1DocumentDocumentIdGetResponse>(
        getGetDocumentApiV1DocumentDocumentIdGetUrl(documentId),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetDocumentApiV1DocumentDocumentIdGetQueryKey = (
    documentId?: number
) => {
    return [`/api/v1/document/${documentId}`] as const;
};

export const getGetDocumentApiV1DocumentDocumentIdGetQueryOptions = <
    TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>,
    TError = HTTPValidationError,
>(
    documentId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                >,
                TError,
                TData
            >
        >;
    }
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getGetDocumentApiV1DocumentDocumentIdGetQueryKey(documentId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>
    > = ({ signal }) =>
        getDocumentApiV1DocumentDocumentIdGet(documentId, signal);

    return {
        queryKey,
        queryFn,
        enabled: !!documentId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetDocumentApiV1DocumentDocumentIdGetQueryResult = NonNullable<
    Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>
>;
export type GetDocumentApiV1DocumentDocumentIdGetQueryError =
    HTTPValidationError;

export function useGetDocumentApiV1DocumentDocumentIdGet<
    TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>,
    TError = HTTPValidationError,
>(
    documentId: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                >,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                    >,
                    TError,
                    Awaited<
                        ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                    >
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
};
export function useGetDocumentApiV1DocumentDocumentIdGet<
    TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>,
    TError = HTTPValidationError,
>(
    documentId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                >,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                    >,
                    TError,
                    Awaited<
                        ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                    >
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetDocumentApiV1DocumentDocumentIdGet<
    TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>,
    TError = HTTPValidationError,
>(
    documentId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                >,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Document
 */

export function useGetDocumentApiV1DocumentDocumentIdGet<
    TData = Awaited<ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>>,
    TError = HTTPValidationError,
>(
    documentId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<typeof getDocumentApiV1DocumentDocumentIdGet>
                >,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
    const queryOptions = getGetDocumentApiV1DocumentDocumentIdGetQueryOptions(
        documentId,
        options
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Delete Document
 */
export type deleteDocumentApiV1DocumentDocumentIdDeleteResponse204 = {
    data: void;
    status: 204;
};

export type deleteDocumentApiV1DocumentDocumentIdDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type deleteDocumentApiV1DocumentDocumentIdDeleteResponseSuccess =
    deleteDocumentApiV1DocumentDocumentIdDeleteResponse204 & {
        headers: Headers;
    };
export type deleteDocumentApiV1DocumentDocumentIdDeleteResponseError =
    deleteDocumentApiV1DocumentDocumentIdDeleteResponse422 & {
        headers: Headers;
    };

export type deleteDocumentApiV1DocumentDocumentIdDeleteResponse =
    | deleteDocumentApiV1DocumentDocumentIdDeleteResponseSuccess
    | deleteDocumentApiV1DocumentDocumentIdDeleteResponseError;

export const getDeleteDocumentApiV1DocumentDocumentIdDeleteUrl = (
    documentId: number
) => {
    return `/api/v1/document/${documentId}`;
};

export const deleteDocumentApiV1DocumentDocumentIdDelete = async (
    documentId: number,
    options?: RequestInit
): Promise<deleteDocumentApiV1DocumentDocumentIdDeleteResponse> => {
    return customFetch<deleteDocumentApiV1DocumentDocumentIdDeleteResponse>(
        getDeleteDocumentApiV1DocumentDocumentIdDeleteUrl(documentId),
        {
            ...options,
            method: "DELETE",
        }
    );
};

export const getDeleteDocumentApiV1DocumentDocumentIdDeleteMutationOptions = <
    TError = HTTPValidationError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteDocumentApiV1DocumentDocumentIdDelete>>,
        TError,
        { documentId: number },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocumentApiV1DocumentDocumentIdDelete>>,
    TError,
    { documentId: number },
    TContext
> => {
    const mutationKey = ["deleteDocumentApiV1DocumentDocumentIdDelete"];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteDocumentApiV1DocumentDocumentIdDelete>>,
        { documentId: number }
    > = (props) => {
        const { documentId } = props ?? {};

        return deleteDocumentApiV1DocumentDocumentIdDelete(documentId);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteDocumentApiV1DocumentDocumentIdDeleteMutationResult =
    NonNullable<
        Awaited<ReturnType<typeof deleteDocumentApiV1DocumentDocumentIdDelete>>
    >;

export type DeleteDocumentApiV1DocumentDocumentIdDeleteMutationError =
    HTTPValidationError;

/**
 * @summary Delete Document
 */
export const useDeleteDocumentApiV1DocumentDocumentIdDelete = <
    TError = HTTPValidationError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<
                ReturnType<typeof deleteDocumentApiV1DocumentDocumentIdDelete>
            >,
            TError,
            { documentId: number },
            TContext
        >;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteDocumentApiV1DocumentDocumentIdDelete>>,
    TError,
    { documentId: number },
    TContext
> => {
    const mutationOptions =
        getDeleteDocumentApiV1DocumentDocumentIdDeleteMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
